security:
  user:
    name: user
    password: pwd
  oauth2:
    resource:
      user-info-uri: "/api/oauth/me"
      filter-order: 3
level:
  org.springframework.security: DEBUG
#server:
#  context-path: /oauthServer
server:
  session:
    cookie:
      name: OAUTH_APPLICATION_SESSION
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: UAA
    key-store: keystore.p12
    key-store-password: UAA@uaa

